name: validate

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run
        uses: docker/bake-action@v4
        with:
          targets: validate